### ISSUE TITLE
Markbot kepps loading

### ISSUE THREAD

**Issue by TriNguyen479** [TriNguyen479/html-validation-fixes#1]
@hellachella

My markbot keeps loading
![image](https://user-images.githubusercontent.com/77295941/108079907-52d5ee80-703d-11eb-81b2-b1ad0367044e.png)

**Comment by hellachella** [comment]
@thomasjbradley Would you mind seeing what is happening?  He is unable to get it running.  He keeps running into this same issue.

**Comment by thomasjbradley** [comment]
In the `Window` menu, open `Activity`. Send me a screenshot of what’s in there.

**Comment by TriNguyen479** [comment]
![image](https://user-images.githubusercontent.com/77295941/108137792-9b67c900-708a-11eb-9114-89e0be308b7c.png)
It's empty.

**Comment by thomasjbradley** [comment]
Have any of the Markbot assignments work?

**Comment by hellachella** [comment]
They haven't, Thomas.

**Comment by hellachella** [comment]
Has this been resolved?

**Comment by thomasjbradley** [comment]
I wonder if it’s the incorrect version of Java installed. Open up “Command Prompt” (I think that’s what it’s called on Windows) & type this: `java -version` and take a screenshot.

**Comment by hellachella** [comment]
@thomasjbradley

If this turns out to be the issue, I can take over from here.

**Comment by TriNguyen479** [comment]
![image](https://user-images.githubusercontent.com/77295941/108582970-5fd83380-7304-11eb-9107-bfac365e7401.png)

**Comment by thomasjbradley** [comment]
I want to see what’s inside the `hosts` file, please run this command:

```
type C:\Windows\System32\drivers\etc\hosts
```

**Comment by TriNguyen479** [comment]
![image](https://user-images.githubusercontent.com/77295941/108615614-fde6ff00-73d3-11eb-9407-c307542811b6.png)
I'm not sure if this is what you ask for

**Comment by thomasjbradley** [comment]
That’s what I wanted to see. Thanks.

Can you send me the pull path to the Markbot application on your computer?

Something like:

```
C:\Program Files\Markbot\Markbot.exe
```

**Comment by TriNguyen479** [comment]
![image](https://user-images.githubusercontent.com/77295941/108640178-2ae3f200-7466-11eb-844f-183df42525eb.png)

**Comment by thomasjbradley** [comment]
Is there something in that Markbot folder named `app.asar` or may an `app` folder?

**Comment by TriNguyen479** [comment]
![image](https://user-images.githubusercontent.com/77295941/108732997-12261b80-74fc-11eb-9aa8-065ae3b71854.png)
Yeah, it's in resources folder
